FROM maven:3.6.3-openjdk-11 AS MAVEN_BUILD

LABEL MAINTAINER='NEOSINIVERSITY'

COPY pom.xml /build/
COPY src /build/src/
#COPY application-docker.properties /build/src/main/resources/application.properties

WORKDIR /build/
RUN mvn package -Dmaven.test.skip=true
#RUN rm -frv /build/src/*

#FROM centos:8.3.2011
FROM centos
RUN yum install -y java-11-openjdk-devel

WORKDIR /app

COPY --from=MAVEN_BUILD /build/target/video-library-0.0.1-SNAPSHOT.jar  /app/

ENTRYPOINT ["java", "-jar", "video-library-0.0.1-SNAPSHOT.jar"]